---
kind: pipeline
name: default

steps:
  - name: test
    image: rust:1.47.0
    commands:
      - rustup component add rustfmt clippy
      - rustc --version
      - cargo clippy --version
      - cargo fmt --version
